# Generated by Django 4.2.18 on 2025-01-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0003_phoneverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
