# Generated by Django 4.2.18 on 2025-02-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='CourseApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='EducationCentres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='education_centres/')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='education_centres/')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_count', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('graduates', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('employees', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_centres', to='CourseApp.category')),
                ('skills', models.ManyToManyField(blank=True, related_name='education_centres', to='CourseApp.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_month', models.IntegerField()),
                ('full_price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('education_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='CourseApp.category')),
                ('education_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='CourseApp.educationcentres')),
                ('skills', models.ManyToManyField(blank=True, related_name='courses', to='CourseApp.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='CourseApp.educationcentres')),
            ],
        ),
    ]
